# Generated by Django 3.0.4 on 2020-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
