# Generated by Django 3.0.4 on 2020-03-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200328_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
    ]
