# Generated by Django 3.0.4 on 2020-03-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200328_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, choices=[('aj', 'Anglický jazyk'), ('b', 'Biologie'), ('cj', 'Český jazyk a literatura'), ('j', 'Jazyky'), ('f', 'Fyzika'), ('ch', 'Chemie'), ('m', 'Matematika'), ('sv', 'Společenské vědy'), ('z', 'Zeměpis'), ('vp', 'Volitelné předměty'), ('other', 'Ostatní')], max_length=100, null=True),
        ),
    ]
